[tasks.check-formatting]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.checks]
run_task = { name = ["lint", "check-formatting"] }   
